CXX = g++
CXXFLAGS = -O3 -Wall -Wextra

build:
	$(CXX) $(CXXFLAGS) insertion-sort.cpp -o insertion-sort
	$(CXX) $(CXXFLAGS) mergesort.cpp -o mergesort

run:
	./insertion-sort
	./mergesort

clean:
	rm insertion-sort mergesort